spring.application.name=FilmesWebBack

# publica a pasta uploads na URL /uploads/**
spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=file:./uploads/

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
